version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_TAG: 3.8
        GH_USER: edg-org
        GH_REPO: edg--template
    ports:
      - "8080:80"
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - db
  db:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authuser
    restart: always
volumes:
  mysql_data: