name: Create and publish a Docker image

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DB_DATABASE: testdb
  DB_USER: root
  DB_PASSWORD: root

jobs:
  build-and-test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_API_VERSION: 0.0.1
          envkey_APP_NAME: "EDG auth API"
          envkey_DATABASE_DIALECT: mysql
          envkey_DATABASE_HOSTNAME: 127.0.0.1
          envkey_DATABASE_USERNAME: ${{ env.DB_USER }}
          envkey_DATABASE_PASSWORD: ${{ env.DB_PASSWORD }}
          envkey_DATABASE_NAME: ${{ env.DB_DATABASE }}
          envkey_DATABASE_PORT: 3306
          envkey_DEBUG_MODE: true
          envkey_GUNICORN_CMD_ARGS: "--reload"
          file_name: .env
          fail_on_empty: false

      - name: Install pipenv
        run: pip install --user pipenv

      - name: Run tests
        run: |
          pipenv install --dev
          pipenv run pytest

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build-and-test-app
    environment:
      name: docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}