name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    uses: edg-org/edg--ops/.github/workflows/test.yml@develop
    with:
      python_version: '3.9'