name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    uses: edg-org/edg--ops/.github/workflows/test.yml@develop
    with:
      python_version: '3.9'
  docker:
    permissions:
      contents: read
      packages: write
    needs: test
    environment:
      name: docker
    uses: edg-org/edg--ops/.github/workflows/docker.yml@develop
    with:
      registry: ghcr.io
      image_name: ${{ github.repository }}